backend = "glx";
vsync = true;

# Basic effects
shadow = true;
corner-radius = 0;
fading = false;

# Detect rounded/transparent windows correctly
detect-rounded-corners = true;
detect-client-opacity = true;

# Reduce unnecessary work
mark-wmwin-focused = true;
mark-ovredir-focused = true;
use-damage = true;
