#!/bin/bash

# Options for the menu
options="Shutdown\nReboot\nLogout\nSuspend\nLock"

# Show dmenu and get the selection
choice=$(echo -e $options | rofi -dmenu -i -p "Power Menu:")

# Execute based on the selection
case "$choice" in
    Shutdown)
        systemctl poweroff
        ;;
    Reboot)
        systemctl reboot
        ;;
    Logout)
        # For example, if using i3
        i3-msg exit
        ;;
    Suspend)
        systemctl suspend
        ;;
    Lock)
        # Example using i3lock
        i3lock
        ;;
esac
