[General]
bookmarks=/home/himadri
lastDisplay=0
maximizedWindow=false
savedPaths=/home/himadri/Downloads, /home/himadri/Downloads/Practical/All/Math/2nd/2, /home/himadri/Downloads/Practical/All/Math/2nd/3, /home/himadri/Downloads/Practical/All/Math/2nd/4, /home/himadri/Downloads/Practical/All/Math/2nd/5, /home/himadri/Downloads/Practical/All/Math/2nd/6, /home/himadri/Downloads/Practical/All/Math/2nd/7, /home/himadri/Downloads/Practical/All/Math/2nd/8, /home/himadri/Downloads/Practical/All/Math/2nd/9
windowGeometry=@Rect(360 129 1200 800)
